### ISSUE TITLE
Upstream improvements from DaCoolX/sheepit-docker

### ISSUE THREAD

**Issue by DaCoolX** [AGSPhoenix/sheepit-docker#15]
Would there be interest if I upstream some changes taken or inspired from my fork and prepared a series of pull request to be integrated?
Things such as
- Dropping root
- Extended Readme
- A greatly expanded and more thoroughly documented Dockerfile

Differences such as renamed filenames or changed environment variables would of course be adjusted to be 100% compatible.
This image is still widely popular and would benefit more people as just keeping it in my personal fork.

**Comment by AGSPhoenix** [comment]
Sure, send it and I'll take a look.
